name: Flutter CI/CD

on:
  pull_request:
    branches: [ main ]

  push:
    branches: [ main ]

jobs:
  test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend/flutter_application_screen

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.4'

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('frontend/flutter_application_screen/pubspec.lock') }}

      - name: Install dependencies
        run: flutter pub get

      - name: Create .env and local.properties files
        env:
          ENV_FILE_CONTENT: ${{ secrets.ENV_FILE }}
          LOCAL_PROPERTIES_CONTENT: ${{ secrets.LOCAL_PROPERTIES }}
        run: |
          echo "$ENV_FILE_CONTENT" > .env
          echo "$LOCAL_PROPERTIES_CONTENT" > android/local.properties

      - name: Analyze
        run: flutter analyze

  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend/flutter_application_screen

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
           flutter-version: '3.41.4'

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('frontend/flutter_application_screen/pubspec.lock') }}

      - name: Install dependencies
        run: flutter pub get

      - name: Create .env and local.properties files
        env:
          ENV_FILE_CONTENT: ${{ secrets.ENV_FILE }}
          LOCAL_PROPERTIES_CONTENT: ${{ secrets.LOCAL_PROPERTIES }}
        run: |
          echo "$ENV_FILE_CONTENT" > .env
          echo "$LOCAL_PROPERTIES_CONTENT" > android/local.properties

      - name: Build APK
        run: flutter build apk --debug

      - name: Rename APK
        run: |
          mv build/app/outputs/flutter-apk/app-debug.apk \
             build/app/outputs/flutter-apk/app-${{ github.ref_name }}-${{ github.run_number }}.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ github.ref_name }}-${{ github.run_number }}
          path: frontend/flutter_application_screen/build/app/outputs/flutter-apk/app-${{ github.ref_name }}-${{ github.run_number }}.apk
